export const sp_endpoints = {
  register: "/api/sp/sp-register",
  verifyOtp: "/api/sp/verify-sp-otp",
  resentOtp: "/api/sp/resend-sp-otp",
  login: "/api/sp/sp-login",
  verifyDetails: "/api/sp/verify-details",
  home: "/api/sp/sp-home",
  serviceCategorys: "/api/sp/categories",
  getProfileDetails: "/api/sp/sp-profile",
  editProfile: "/api/sp/edit-profile",
  editPassword: "/api/sp/edit-password",
  addSlot: "/api/sp/add-slot",
  getSlots: "/api/sp/get-slots",
  getDomains: "/api/sp/get-domains",
  editSlot: "/api/sp/edit-slot",
  getBookings: "/api/sp/get-bookings",
  refund: "/api/payment/refund",
  updateBookingStatus: "/api/sp/update-booking-status",
  leave: "/api/sp/leave",
  recordings: "/api/recordings/:userId",
};
