export const user_endpoints = {
  register: "/api/user/user-register",
  googleRegister: "/api/user/google-register",
  verify_otp: "/api/user/verify-user-otp",
  logout: "/api/user/logout",
  resend_otp: "/api/user/resend-otp",
  login: "/api/user/user-login",
  googleLogin: "/api/user/google-login",
  home: "/api/user/user-home",
  verifyDetails: "/api/user/verify-userdetails",
  userProfile: "/api/user/get-profile",
  editProfile: "/api/user/edit-profile",
  editPassword: "/api/user/edit-password",
  serviceProviders: "/api/user/service-providers",
  serviceProvidersPublic: "/api/user/public/service-providers",
  getServiceProviderDetails: "/api/user/sp-details",
  getBlogs: "/api/user/blogs",
  getSlotDetails: "/api/user/slot-details",
  getScheduledBookings: "/api/user/get-bookings",
  makePayment: "/api/payment/create-payment",
  cancelBooking: "/api/payment/cancelBooking",
  submitComplaint: '/api/user/complaints',
  getComplaints: '/api/user/complaints',
};
