export const user_endpoints = {
  register: "/user/user-register",
  verify_otp: "/user/verify-user-otp",
  logout: "/user/logout",
  resend_otp: "/user/resend-otp",
  login: "/user/user-login",
  home: "/user/user-home",
  verifyDetails: "/user/verify-userdetails",
  userProfile: "/user/get-profile",
  editProfile: "/user/edit-profile",
  editPassword: "/user/edit-password",
  serviceProviders: "/user/service-providers",
  getServiceProviderDetails: "/user/sp-details",
  getBlogs: "/user/blogs",
  getSlotDetails: "/user/slot-details",
  getScheduledBookings: "/user/get-bookings",
  makePayment: "/payment/create-payment",
  cancelBooking: "/payment/cancelBooking",
};
